// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpSthzoR5oeRRv3-hVAOnoQKO2HAGnFQk',
    appId: '1:304399193254:web:50eb30c65bc0865b9ed067',
    messagingSenderId: '304399193254',
    projectId: 'chattingapp-b8bba',
    authDomain: 'chattingapp-b8bba.firebaseapp.com',
    databaseURL: 'https://chattingapp-b8bba-default-rtdb.firebaseio.com',
    storageBucket: 'chattingapp-b8bba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_2cdXtOr0I2VV0gGbHa-Dn5-EvOTHLYg',
    appId: '1:304399193254:android:0a998ffd6d502eeb9ed067',
    messagingSenderId: '304399193254',
    projectId: 'chattingapp-b8bba',
    databaseURL: 'https://chattingapp-b8bba-default-rtdb.firebaseio.com',
    storageBucket: 'chattingapp-b8bba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDubJSAVKh_jUu2XKXSCbs3owA0BgFX3ic',
    appId: '1:304399193254:ios:dbafc2766b62aaa89ed067',
    messagingSenderId: '304399193254',
    projectId: 'chattingapp-b8bba',
    databaseURL: 'https://chattingapp-b8bba-default-rtdb.firebaseio.com',
    storageBucket: 'chattingapp-b8bba.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDubJSAVKh_jUu2XKXSCbs3owA0BgFX3ic',
    appId: '1:304399193254:ios:d2399e6be1fb5bb09ed067',
    messagingSenderId: '304399193254',
    projectId: 'chattingapp-b8bba',
    databaseURL: 'https://chattingapp-b8bba-default-rtdb.firebaseio.com',
    storageBucket: 'chattingapp-b8bba.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
